import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9ff",
        "surface-container-low": "#f1f3ff",
        "primary-container": "#00855d",
        background: "#f9f9ff",
        "on-primary-fixed-variant": "#005137",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#566660",
        secondary: "#52625c",
        "on-error": "#ffffff",
        tertiary: "#006947",
        "inverse-primary": "#68dba9",
        "secondary-container": "#d3e3dc",
        "on-tertiary-container": "#f5fff6",
        "on-primary-container": "#f5fff7",
        "primary-fixed": "#85f8c4",
        "tertiary-container": "#00855b",
        "surface-bright": "#f9f9ff",
        "error-container": "#ffdad6",
        "surface-variant": "#dce2f7",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#bccac0",
        "primary-fixed-dim": "#68dba9",
        "on-secondary-fixed": "#101e1a",
        "on-secondary-fixed-variant": "#3b4a44",
        "on-background": "#141b2b",
        error: "#ba1a1a",
        "inverse-on-surface": "#edf0ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "secondary-fixed": "#d5e6df",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#141b2b",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-tint": "#006c4a",
        outline: "#6d7a72",
        "on-primary-fixed": "#002114",
        "inverse-surface": "#293040",
        "secondary-fixed-dim": "#bacac3",
        "on-tertiary-fixed": "#002113",
        primary: "#006948",
        "surface-container": "#e9edff",
        "on-surface-variant": "#3d4a42",
        "surface-container-high": "#e1e8fd",
        "surface-dim": "#d3daef",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      // Custom spacing scale used throughout the Stitch designs (p-md, gap-lg, etc.)
      spacing: {
        lg: "48px",
        xl: "80px",
        "container-max": "1200px",
        base: "8px",
        sm: "12px",
        xs: "4px",
        gutter: "24px",
        md: "24px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        serif: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-inter)", "Inter", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        caption: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      // Role-based type scale from the Stitch design system
      fontSize: {
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease forwards",
        "slide-in": "slide-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
