import {
  Landmark,
  Wallet,
  Plus,
  ClipboardCheck,
  AtSign,
  Lock,
  UserCog,
  Calculator,
  Eye,
  Crown,
  Building2,
  ArrowLeft,
  ArrowRight,
  ClipboardList,
  Sparkles,
  Ban,
  Zap,
  Bookmark,
  BookOpen,
  Briefcase,
  CalendarPlus,
  Calendar,
  CalendarDays,
  Megaphone,
  CreditCard,
  PartyPopper,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  X,
  CloudUpload,
  Code,
  ArrowLeftRight,
  Ticket,
  Copy,
  FolderPlus,
  Moon,
  Trash2,
  Users,
  UsersRound,
  MinusCircle,
  Download,
  Pencil,
  FileEdit,
  Cog,
  AlertCircle,
  CalendarCheck,
  CalendarX,
  ChevronUp,
  ChevronDown,
  Compass,
  PlaneTakeoff,
  FolderOpen,
  MessageSquare,
  Sigma,
  Gavel,
  ShieldCheck,
  Headset,
  ScrollText,
  LineChart,
  Globe,
  Globe2,
  Trophy,
  Sun,
  MapPin,
  LogIn,
  LogOut,
  Mail,
  Map,
  MailCheck,
  Stethoscope,
  Menu,
  Award,
  ExternalLink,
  Palette,
  Banknote,
  User,
  UserPlus,
  UserCheck,
  Brain,
  Receipt,
  Save,
  PiggyBank,
  GraduationCap,
  FlaskConical,
  Search,
  SearchX,
  Send,
  Share2,
  Shield,
  ArrowDown,
  Star,
  StopCircle,
  Target,
  GanttChart,
  TrendingUp,
  BadgeCheck,
  Rows3,
  HandHeart,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

/**
 * Every icon name this app used to render as a Material Symbols ligature
 * (e.g. "arrow_forward", "bookmark_border"), mapped to a bundled lucide-react
 * component. Bundled SVGs can't 404/fail to load the way an external Google
 * Fonts icon-font request can — that font request failing (blocked network,
 * ad blocker, slow connection) is what used to render raw ligature text like
 * "auto_awesome" on screen instead of an icon.
 */
const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  admin_panel_settings: UserCog,
  calculate: Calculator,
  account_balance_wallet: Wallet,
  add: Plus,
  add_task: ClipboardCheck,
  alternate_email: AtSign,
  architecture: Building2,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  assignment: ClipboardList,
  assignment_turned_in: ClipboardCheck,
  auto_awesome: Sparkles,
  block: Ban,
  bolt: Zap,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  business_center: Briefcase,
  calendar_add_on: CalendarPlus,
  calendar_month: Calendar,
  campaign: Megaphone,
  card_membership: CreditCard,
  celebration: PartyPopper,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: CloudUpload,
  code: Code,
  compare_arrows: ArrowLeftRight,
  confirmation_number: Ticket,
  content_copy: Copy,
  create_new_folder: FolderPlus,
  dark_mode: Moon,
  delete: Trash2,
  delete_sweep: Trash2,
  diversity_1: Users,
  diversity_3: UsersRound,
  do_not_disturb_on: MinusCircle,
  download: Download,
  east: ArrowRight,
  edit: Pencil,
  edit_note: FileEdit,
  engineering: Cog,
  error: AlertCircle,
  event: CalendarDays,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  flight_takeoff: PlaneTakeoff,
  folder_open: FolderOpen,
  forum: MessageSquare,
  functions: Sigma,
  gavel: Gavel,
  gpp_good: ShieldCheck,
  groups: Users,
  headset_mic: Headset,
  history_edu: ScrollText,
  insights: LineChart,
  language: Globe,
  leaderboard: Trophy,
  light_mode: Sun,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  map: Map,
  mark_email_read: MailCheck,
  medical_services: Stethoscope,
  menu: Menu,
  menu_book: BookOpen,
  military_tech: Award,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  person_check: UserCheck,
  psychology: Brain,
  public: Globe2,
  request_quote: Receipt,
  save: Save,
  savings: PiggyBank,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  send: Send,
  share: Share2,
  shield: Shield,
  south: ArrowDown,
  star: Star,
  stop: StopCircle,
  stop_circle: StopCircle,
  target: Target,
  task_alt: CheckCircle2,
  timeline: GanttChart,
  travel_explore: Globe2,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  view_agenda: Rows3,
  visibility: Eye,
  volunteer_activism: HandHeart,
  workspace_premium: Crown,
};

/**
 * Drop-in replacement for `<span className="material-symbols-outlined …">name</span>`.
 * Sized in `em` so it inherits whatever font-size / text-color utility classes
 * are passed in `className`, matching how the old ligature icons were sized.
 */
export function Icon({
  name,
  className,
  filled = false,
}: {
  name: string;
  className?: string;
  filled?: boolean;
}) {
  const Component = ICONS[name] ?? HelpCircle;
  return (
    <Component
      aria-hidden="true"
      className={className}
      style={{ width: "1em", height: "1em", verticalAlign: "middle" }}
      fill={filled ? "currentColor" : "none"}
    />
  );
}
